apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab1-api
  template:
    metadata:
      labels:
        app: lab1-api
    spec:
      containers:
        - name: lab1-api
          image: lab1-api:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
